<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ParticipantesConjuntos', 'doctrine');

/**
 * BaseParticipantesConjuntos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_usuario
 * @property integer $id_conjunto
 * @property integer $id_tipo_conjunto
 * @property integer $id_tipo_permissao_conjunto
 * 
 * @method integer                getIdUsuario()                  Returns the current record's "id_usuario" value
 * @method integer                getIdConjunto()                 Returns the current record's "id_conjunto" value
 * @method integer                getIdTipoConjunto()             Returns the current record's "id_tipo_conjunto" value
 * @method integer                getIdTipoPermissaoConjunto()    Returns the current record's "id_tipo_permissao_conjunto" value
 * @method ParticipantesConjuntos setIdUsuario()                  Sets the current record's "id_usuario" value
 * @method ParticipantesConjuntos setIdConjunto()                 Sets the current record's "id_conjunto" value
 * @method ParticipantesConjuntos setIdTipoConjunto()             Sets the current record's "id_tipo_conjunto" value
 * @method ParticipantesConjuntos setIdTipoPermissaoConjunto()    Sets the current record's "id_tipo_permissao_conjunto" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseParticipantesConjuntos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('participantes_conjuntos');
        $this->hasColumn('id_usuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_conjunto', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_tipo_conjunto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_tipo_permissao_conjunto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}