<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LogsSistema', 'doctrine');

/**
 * BaseLogsSistema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_log_sistema
 * @property integer $id_usuario
 * @property string $descricao
 * @property string $parametros
 * @property integer $tipo_log
 * @property timestamp $data_publicacao
 * 
 * @method integer     getIdLogSistema()    Returns the current record's "id_log_sistema" value
 * @method integer     getIdUsuario()       Returns the current record's "id_usuario" value
 * @method string      getDescricao()       Returns the current record's "descricao" value
 * @method string      getParametros()      Returns the current record's "parametros" value
 * @method integer     getTipoLog()         Returns the current record's "tipo_log" value
 * @method timestamp   getDataPublicacao()  Returns the current record's "data_publicacao" value
 * @method LogsSistema setIdLogSistema()    Sets the current record's "id_log_sistema" value
 * @method LogsSistema setIdUsuario()       Sets the current record's "id_usuario" value
 * @method LogsSistema setDescricao()       Sets the current record's "descricao" value
 * @method LogsSistema setParametros()      Sets the current record's "parametros" value
 * @method LogsSistema setTipoLog()         Sets the current record's "tipo_log" value
 * @method LogsSistema setDataPublicacao()  Sets the current record's "data_publicacao" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogsSistema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logs_sistema');
        $this->hasColumn('id_log_sistema', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_usuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descricao', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('parametros', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('tipo_log', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('data_publicacao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}