<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MensagensDestinatarios', 'doctrine');

/**
 * BaseMensagensDestinatarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_mensagem
 * @property integer $id_usuario_destinatario
 * @property integer $id_usuario_remetente
 * 
 * @method integer                getIdMensagem()              Returns the current record's "id_mensagem" value
 * @method integer                getIdUsuarioDestinatario()   Returns the current record's "id_usuario_destinatario" value
 * @method integer                getIdUsuarioRemetente()      Returns the current record's "id_usuario_remetente" value
 * @method MensagensDestinatarios setIdMensagem()              Sets the current record's "id_mensagem" value
 * @method MensagensDestinatarios setIdUsuarioDestinatario()   Sets the current record's "id_usuario_destinatario" value
 * @method MensagensDestinatarios setIdUsuarioRemetente()      Sets the current record's "id_usuario_remetente" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensagensDestinatarios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mensagens_destinatarios');
        $this->hasColumn('id_mensagem', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario_destinatario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_usuario_remetente', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}