<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Documentos', 'doctrine');

/**
 * BaseDocumentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_documento
 * @property integer $id_usuario
 * @property integer $id_pasta
 * @property string $nome_arquivo
 * @property integer $is_codigo_fonte
 * @property string $repositorio_github
 * @property integer $ordenacao
 * @property string $nome_documento
 * 
 * @method integer    getIdDocumento()        Returns the current record's "id_documento" value
 * @method integer    getIdUsuario()          Returns the current record's "id_usuario" value
 * @method integer    getIdPasta()            Returns the current record's "id_pasta" value
 * @method string     getNomeArquivo()        Returns the current record's "nome_arquivo" value
 * @method integer    getIsCodigoFonte()      Returns the current record's "is_codigo_fonte" value
 * @method string     getRepositorioGithub()  Returns the current record's "repositorio_github" value
 * @method integer    getOrdenacao()          Returns the current record's "ordenacao" value
 * @method string     getNomeDocumento()      Returns the current record's "nome_documento" value
 * @method Documentos setIdDocumento()        Sets the current record's "id_documento" value
 * @method Documentos setIdUsuario()          Sets the current record's "id_usuario" value
 * @method Documentos setIdPasta()            Sets the current record's "id_pasta" value
 * @method Documentos setNomeArquivo()        Sets the current record's "nome_arquivo" value
 * @method Documentos setIsCodigoFonte()      Sets the current record's "is_codigo_fonte" value
 * @method Documentos setRepositorioGithub()  Sets the current record's "repositorio_github" value
 * @method Documentos setOrdenacao()          Sets the current record's "ordenacao" value
 * @method Documentos setNomeDocumento()      Sets the current record's "nome_documento" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documentos');
        $this->hasColumn('id_documento', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_pasta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nome_arquivo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_codigo_fonte', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('repositorio_github', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('ordenacao', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nome_documento', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}