<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Conteudos', 'doctrine');

/**
 * BaseConteudos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_conteudo
 * @property integer $id_tipo_conjunto
 * @property integer $id_conjunto
 * @property integer $id_super_tipo
 * @property string $nome
 * @property string $descricao
 * @property integer $enviar_email_criador
 * @property string $nome_repositorio_github
 * @property integer $tema_aula
 * 
 * @method integer   getIdConteudo()              Returns the current record's "id_conteudo" value
 * @method integer   getIdTipoConjunto()          Returns the current record's "id_tipo_conjunto" value
 * @method integer   getIdConjunto()              Returns the current record's "id_conjunto" value
 * @method integer   getIdSuperTipo()             Returns the current record's "id_super_tipo" value
 * @method string    getNome()                    Returns the current record's "nome" value
 * @method string    getDescricao()               Returns the current record's "descricao" value
 * @method integer   getEnviarEmailCriador()      Returns the current record's "enviar_email_criador" value
 * @method string    getNomeRepositorioGithub()   Returns the current record's "nome_repositorio_github" value
 * @method integer   getTemaAula()                Returns the current record's "tema_aula" value
 * @method Conteudos setIdConteudo()              Sets the current record's "id_conteudo" value
 * @method Conteudos setIdTipoConjunto()          Sets the current record's "id_tipo_conjunto" value
 * @method Conteudos setIdConjunto()              Sets the current record's "id_conjunto" value
 * @method Conteudos setIdSuperTipo()             Sets the current record's "id_super_tipo" value
 * @method Conteudos setNome()                    Sets the current record's "nome" value
 * @method Conteudos setDescricao()               Sets the current record's "descricao" value
 * @method Conteudos setEnviarEmailCriador()      Sets the current record's "enviar_email_criador" value
 * @method Conteudos setNomeRepositorioGithub()   Sets the current record's "nome_repositorio_github" value
 * @method Conteudos setTemaAula()                Sets the current record's "tema_aula" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConteudos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('conteudos');
        $this->hasColumn('id_conteudo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('id_tipo_conjunto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_conjunto', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_super_tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nome', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descricao', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('enviar_email_criador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nome_repositorio_github', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('tema_aula', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}