<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ignorados', 'doctrine');

/**
 * BaseIgnorados
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_usuario
 * @property integer $id_usuario_ignorado
 * @property timestamp $data_ignoraracao
 * 
 * @method integer   getIdUsuario()           Returns the current record's "id_usuario" value
 * @method integer   getIdUsuarioIgnorado()   Returns the current record's "id_usuario_ignorado" value
 * @method timestamp getDataIgnoraracao()     Returns the current record's "data_ignoraracao" value
 * @method Ignorados setIdUsuario()           Sets the current record's "id_usuario" value
 * @method Ignorados setIdUsuarioIgnorado()   Sets the current record's "id_usuario_ignorado" value
 * @method Ignorados setDataIgnoraracao()     Sets the current record's "data_ignoraracao" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIgnorados extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ignorados');
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario_ignorado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('data_ignoraracao', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}