<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mensagens', 'doctrine');

/**
 * BaseMensagens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_mensagem
 * @property integer $id_usuario
 * @property string $conteudo
 * 
 * @method integer   getIdMensagem()  Returns the current record's "id_mensagem" value
 * @method integer   getIdUsuario()   Returns the current record's "id_usuario" value
 * @method string    getConteudo()    Returns the current record's "conteudo" value
 * @method Mensagens setIdMensagem()  Sets the current record's "id_mensagem" value
 * @method Mensagens setIdUsuario()   Sets the current record's "id_usuario" value
 * @method Mensagens setConteudo()    Sets the current record's "conteudo" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensagens extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mensagens');
        $this->hasColumn('id_mensagem', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('conteudo', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}