<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Imagens', 'doctrine');

/**
 * BaseImagens
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_imagem
 * @property integer $id_usuario
 * @property integer $id_pasta
 * @property string $nome_arquivo
 * @property integer $ordenacao
 * 
 * @method integer getIdImagem()     Returns the current record's "id_imagem" value
 * @method integer getIdUsuario()    Returns the current record's "id_usuario" value
 * @method integer getIdPasta()      Returns the current record's "id_pasta" value
 * @method string  getNomeArquivo()  Returns the current record's "nome_arquivo" value
 * @method integer getOrdenacao()    Returns the current record's "ordenacao" value
 * @method Imagens setIdImagem()     Sets the current record's "id_imagem" value
 * @method Imagens setIdUsuario()    Sets the current record's "id_usuario" value
 * @method Imagens setIdPasta()      Sets the current record's "id_pasta" value
 * @method Imagens setNomeArquivo()  Sets the current record's "nome_arquivo" value
 * @method Imagens setOrdenacao()    Sets the current record's "ordenacao" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImagens extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('imagens');
        $this->hasColumn('id_imagem', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_pasta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nome_arquivo', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('ordenacao', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}