<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuarios', 'doctrine');

/**
 * BaseUsuarios
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_usuario
 * @property integer $nivel_escolaridade
 * @property string $nome
 * @property string $login
 * @property string $senha
 * @property string $email
 * @property string $endereco
 * @property string $habilidades
 * @property string $curso
 * @property string $site
 * @property string $site_empresa
 * @property date $data_nascimento
 * @property integer $sexo
 * @property integer $administrador
 * @property string $sobre_mim
 * @property integer $ativo
 * @property string $imagem_perfil
 * @property string $twitter
 * @property string $parametros_privacidade
 * @property integer $aula_robolivre
 * @property string $profissao
 * @property string $escola
 * @property string $empresa
 * @property timestamp $data_criacao_perfil
 * @property string $parametros_email
 * @property string $token
 * @property integer $email_novo
 * 
 * @method integer   getIdUsuario()              Returns the current record's "id_usuario" value
 * @method integer   getNivelEscolaridade()      Returns the current record's "nivel_escolaridade" value
 * @method string    getNome()                   Returns the current record's "nome" value
 * @method string    getLogin()                  Returns the current record's "login" value
 * @method string    getSenha()                  Returns the current record's "senha" value
 * @method string    getEmail()                  Returns the current record's "email" value
 * @method string    getEndereco()               Returns the current record's "endereco" value
 * @method string    getHabilidades()            Returns the current record's "habilidades" value
 * @method string    getCurso()                  Returns the current record's "curso" value
 * @method string    getSite()                   Returns the current record's "site" value
 * @method string    getSiteEmpresa()            Returns the current record's "site_empresa" value
 * @method date      getDataNascimento()         Returns the current record's "data_nascimento" value
 * @method integer   getSexo()                   Returns the current record's "sexo" value
 * @method integer   getAdministrador()          Returns the current record's "administrador" value
 * @method string    getSobreMim()               Returns the current record's "sobre_mim" value
 * @method integer   getAtivo()                  Returns the current record's "ativo" value
 * @method string    getImagemPerfil()           Returns the current record's "imagem_perfil" value
 * @method string    getTwitter()                Returns the current record's "twitter" value
 * @method string    getParametrosPrivacidade()  Returns the current record's "parametros_privacidade" value
 * @method integer   getAulaRobolivre()          Returns the current record's "aula_robolivre" value
 * @method string    getProfissao()              Returns the current record's "profissao" value
 * @method string    getEscola()                 Returns the current record's "escola" value
 * @method string    getEmpresa()                Returns the current record's "empresa" value
 * @method timestamp getDataCriacaoPerfil()      Returns the current record's "data_criacao_perfil" value
 * @method string    getParametrosEmail()        Returns the current record's "parametros_email" value
 * @method string    getToken()                  Returns the current record's "token" value
 * @method integer   getEmailNovo()              Returns the current record's "email_novo" value
 * @method Usuarios  setIdUsuario()              Sets the current record's "id_usuario" value
 * @method Usuarios  setNivelEscolaridade()      Sets the current record's "nivel_escolaridade" value
 * @method Usuarios  setNome()                   Sets the current record's "nome" value
 * @method Usuarios  setLogin()                  Sets the current record's "login" value
 * @method Usuarios  setSenha()                  Sets the current record's "senha" value
 * @method Usuarios  setEmail()                  Sets the current record's "email" value
 * @method Usuarios  setEndereco()               Sets the current record's "endereco" value
 * @method Usuarios  setHabilidades()            Sets the current record's "habilidades" value
 * @method Usuarios  setCurso()                  Sets the current record's "curso" value
 * @method Usuarios  setSite()                   Sets the current record's "site" value
 * @method Usuarios  setSiteEmpresa()            Sets the current record's "site_empresa" value
 * @method Usuarios  setDataNascimento()         Sets the current record's "data_nascimento" value
 * @method Usuarios  setSexo()                   Sets the current record's "sexo" value
 * @method Usuarios  setAdministrador()          Sets the current record's "administrador" value
 * @method Usuarios  setSobreMim()               Sets the current record's "sobre_mim" value
 * @method Usuarios  setAtivo()                  Sets the current record's "ativo" value
 * @method Usuarios  setImagemPerfil()           Sets the current record's "imagem_perfil" value
 * @method Usuarios  setTwitter()                Sets the current record's "twitter" value
 * @method Usuarios  setParametrosPrivacidade()  Sets the current record's "parametros_privacidade" value
 * @method Usuarios  setAulaRobolivre()          Sets the current record's "aula_robolivre" value
 * @method Usuarios  setProfissao()              Sets the current record's "profissao" value
 * @method Usuarios  setEscola()                 Sets the current record's "escola" value
 * @method Usuarios  setEmpresa()                Sets the current record's "empresa" value
 * @method Usuarios  setDataCriacaoPerfil()      Sets the current record's "data_criacao_perfil" value
 * @method Usuarios  setParametrosEmail()        Sets the current record's "parametros_email" value
 * @method Usuarios  setToken()                  Sets the current record's "token" value
 * @method Usuarios  setEmailNovo()              Sets the current record's "email_novo" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarios extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuarios');
        $this->hasColumn('id_usuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nivel_escolaridade', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('login', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('senha', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('endereco', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('habilidades', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('curso', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('site', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('site_empresa', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('data_nascimento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sexo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('administrador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sobre_mim', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ativo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '1',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('imagem_perfil', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('twitter', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('parametros_privacidade', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('aula_robolivre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('profissao', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('escola', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('empresa', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('data_criacao_perfil', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('parametros_email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'i[i] a[a]',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('email_novo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}