<?php

/**
 * ArquivosAnexosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArquivosAnexosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArquivosAnexosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArquivosAnexos');
    }
}