<?php

/**
 * ComunidadesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComunidadesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComunidadesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comunidades');
    }
}