<?php

/**
 * ConjuntosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConjuntosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConjuntosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conjuntos');
    }
}