<?php

/**
 * ImagensTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImagensTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImagensTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Imagens');
    }
}