<?php

/**
 * LogsSistemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogsSistemaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogsSistemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogsSistema');
    }
}