<?php

/**
 * MensagensTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensagensTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensagensTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mensagens');
    }
}