<?php

/**
 * ParticipantesConjuntosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParticipantesConjuntosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParticipantesConjuntosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ParticipantesConjuntos');
    }
}