<?php

/**
 * PastasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pastas');
    }
}