<?php

/**
 * Publicacoes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robolivre
 * @subpackage model
 * * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Publicacoes extends BasePublicacoes {

    private $comentarios = array();
    private $nomeUsuario;
    
    public function getNomeUsuario() {
        return $this->nomeUsuario;
    }

    public function setNomeUsuario($nome_usuario) {
        $this->nomeUsuario = $nome_usuario;
    }

    public function getComentarios() {
        return array_reverse($this->comentarios);
    }

    public function setComentarios($comentarios) {
        $this->comentarios = $comentarios;
    }

    public function adicionarComentario(Publicacoes $publicacao) {
        $this->comentarios[$publicacao->getIdPublicacao()] = $publicacao;
    }

}
