<?php

/**
 * SuperTiposTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SuperTiposTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SuperTiposTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SuperTipos');
    }
}