<?php

/**
 * TiposConjuntosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposConjuntosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposConjuntosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiposConjuntos');
    }
}