<?php

/**
 * VideosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Videos');
    }
}