<?php

/**
 * ConjuntosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConjuntosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConjuntosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conjuntos');
    }
    
    
    public function getSlug($id_conjunto) {
        
        $q = Doctrine_Query::create()
                ->select('slug')
                ->from('Conjuntos')
                ->where("id_conjunto = '$id_conjunto'");
        

        $resultado = $q->fetchArray();

        if ($resultado){ 
            foreach ($resultado as $reg) 
                return $reg['slug'];
        }

        return false;
    }
}