<?php

/**
 * Conteudos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robolivre
 * @subpackage model
 ** @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Conteudos extends BaseConteudos
{
    
    private $tipoUsuario;
    private $tipoSolicitacao;
    private $conjunto;
    private $nomeProprietario;
    
    const PROPRIETARIO = -1;
    const NAO_PARTICIPA = -2;
    
    const SEM_SOLICITACAO = 2;
    const PARTICIPANTE = 1;
    const SOLICITADA_PARTICIPACAO = 0;
    const AGUARDANDO_CONFIRMACAO = 3;
    
    public function setEnviarEmailCriador($valor) {
        parent::_set('enviar_email_criador', ($valor=="on")?1:0);
        return $this;
    }
        
    public function getTipoSolicitacao() {
        return $this->tipoSolicitacao;
    }

    public function setTipoSolicitacao($tipoSolicitacao) {
        $this->tipoSolicitacao = $tipoSolicitacao;
    }
    
    public function getTipoUsuario() {
        return $this->tipoUsuario;
    }

    public function setTipoUsuario($tipoUsuario) {
        $this->tipoUsuario = $tipoUsuario;
    }
    
    public function getConjunto() {
        return $this->conjunto;
    }

    public function setConjunto($conjunto) {
        $this->conjunto = $conjunto;
    }
    
    public function getNomeProprietario() {
        if(!isset($this->nomeProprietario)){
            if(isset($this->conjunto) && $this->conjunto->getIdUsuario() == UsuarioLogado::getInstancia()->getIdUsuario()){
                $this->nomeProprietario = UsuarioLogado::getInstancia()->getNome();
            }
        }
        return $this->nomeProprietario;
    }

    public function setNomeProprietario($nomeProprietario) {
        $this->nomeProprietario = $nomeProprietario;
    }
}
