<?php

/**
 * DiariosBordoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DiariosBordoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DiariosBordoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DiariosBordo');
    }
}