<?php

/**
 * MensagensDestinatariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensagensDestinatariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensagensDestinatariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MensagensDestinatarios');
    }
}