<?php

/**
 * ParticipantesConjuntos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robolivre
 * @subpackage model
 ** @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ParticipantesConjuntos extends BaseParticipantesConjuntos
{
    public function solicitarParticipacao($id_conjunto){
        parent::_set('id_usuario', UsuarioLogado::getInstancia()->getIdUsuario());
        parent::_set('id_conjunto', $id_conjunto);
        parent::_set('id_tipo_conjunto', Conjuntos::TIPO_CONTEUDO);
    }
}
