<?php

/**
 * Publicacoes
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robolivre
 * @subpackage model
 * * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Publicacoes extends BasePublicacoes {

    private $grupoComentarios = array();
    private $nomeUsuario;
    private $nomeUsuarioReferencia;
    private $nomeConjunto;
    
    public function getNomeUsuarioReferencia() {
        return $this->nomeUsuarioReferencia;
    }

    public function setNomeUsuarioReferencia($nomeUsuarioReferencia) {
        $this->nomeUsuarioReferencia = $nomeUsuarioReferencia;
    }

    public function getNomeConjunto() {
        return $this->nomeConjunto;
    }

    public function setNomeConjunto($nomeConjunto) {
        $this->nomeConjunto = $nomeConjunto;
    }

    public function getNomeUsuario() {
        return $this->nomeUsuario;
    }

    public function setNomeUsuario($nome_usuario) {
        $this->nomeUsuario = $nome_usuario;
    }

    public function getGrupoComentarios() {
        return array_reverse($this->grupoComentarios);
    }

    public function setGrupoComentarios($comentarios) {
        $this->grupoComentarios = $comentarios;
    }

    public function adicionarPublicacaoComentario(Publicacoes $publicacao) {
        $this->grupoComentarios[$publicacao->getIdPublicacao()] = $publicacao;
    }

}
