<?php

/**
 * TagsConteudos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robolivre
 * @subpackage model
 ** @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TagsConteudos extends BaseTagsConteudos
{
    private $conteudo;
    
    public function getConteudo() {
        
        if($this->conteudo==null){
            $this->conteudo = new Conteudos();
        }
        
        return $this->conteudo;
    }

    public function setConteudo($conteudo) {
        $this->conteudo = $conteudo;
    }
    
    public function getNomeConteudo(){
        return $this->getConteudo()->getNome();
    }
}
