<?php

/**
 * TagsConteudosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagsConteudosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TagsConteudosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TagsConteudos');
    }
}