<?php

/**
 * TiposPermissoesConjuntosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposPermissoesConjuntosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposPermissoesConjuntosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiposPermissoesConjuntos');
    }
}