<?php

/**
 * Documentos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robolivre
 * @subpackage model
 ** @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Documentos extends BaseDocumentos
{
    public function getExtensaoArquivo(){
        $arquivo = $this->getNomeArquivo();
        $array = explode(".", $arquivo);
        return end($array);
    }
}
