<?php

/**
 * IgnoradosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IgnoradosTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object IgnoradosTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Ignorados');
    }

    public function ignorar($id_usuario_ignorado) {
        if (!$this->estaIgnorado($id_usuario_ignorado)) {
            $usuario = UsuarioLogado::getInstancia()->getIdUsuario();
            $sql = "INSERT INTO ignorados (id_usuario, id_usuario_ignorado) VALUES (:u, :uIgnored)";
            $conn = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
            $stmt = $conn->prepare($sql);
            $stmt->bindParam(':u', $usuario);
            $stmt->bindParam(':uIgnored', $id_usuario_ignorado);
            if ($stmt->execute()) {
                $logSistema = new LogsSistema();
                $logSistema->setIdUsuario(UsuarioLogado::getInstancia()->getIdUsuario());
                $logSistema->setTipoLog(LogsSistema::IGNOROU_USUARIO);
                $logSistema->setDescricao(LogsSistema::getDescricaoPeloTipo(LogsSistema::IGNOROU_USUARIO));
                $logSistema->setDataPublicacao(date('Y-m-d H:i:s'));
                $logSistema->setParametros(
                        "IP:" . UsuarioLogado::getInstancia()->getEnderecoRemoto() . LogsSistema::SEPARADOR .
                        "ID_USUARIO: " . $id_usuario_ignorado
                );
                $logSistema->save();
            }
        }
    }

    public function estaIgnorado($id_usuario) {
        $sql = "SELECT id_usuario_ignorado FROM ignorados WHERE id_usuario_ignorado = :id";
        $conn = Doctrine_Manager::getInstance()->getCurrentConnection()->getDbh();
        $stmt = $conn->prepare($sql);
        $stmt->bindParam(':id', $id_usuario);
        $stmt->execute();
        if ($stmt->rowCount()) {
            return true;
        }
        return false;
    }

}