<?php

/**
 * Pastas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    robolivre
 * @subpackage model
 ** @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Pastas extends BasePastas
{
    const TIPO_PASTA_PUBLICACOES = 1;
    const TIPO_PASTA_ANEXOS_CONJUNTO = 2;
    const TIPO_PASTA_PUBLICACOES_CONJUNTO = 4;
    const TIPO_PASTA_CRIADA_USUARIO = 3;
}
