<?php

/**
 * PastasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PastasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PastasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pastas');
    }
    
    
    public function getPastaUsuario($idUsuario = null,$tipoPasta = null,$idConjunto = null,$tipoConjunto = null){
        
        if($idUsuario==null){
            $idUsuario = UsuarioLogado::getInstancia()->getIdUsuario();
        }
        
        $q = Doctrine_Query::create()
                ->select('*')
                ->from('Pastas')
                ->where("id_usuario =  $idUsuario");
                if($idConjunto==null){
                    $q = $q->andWhere("id_conjunto IS NULL");
                }else{
                    $q = $q->andWhere("id_conjunto = $idConjunto")->andWhere("id_tipo_conjunto = $tipoConjunto");
                }
                
                if($tipoPasta!=null){
                    $q = $q->andWhere("tipo_pasta = $tipoPasta");
                }
                
                
        $resultado = $q->fetchArray();
        
        if ($resultado) {
            $arrayRetorno = array();
            $cont = count($resultado);
            foreach ($resultado as $reg) {
                $pasta = new Pastas();
                $pasta->setIdPasta($reg['id_pasta']);
                $pasta->setIdUsuario($reg['id_usuario']);
                $pasta->setNome($reg['nome']);
                $pasta->setDescricao($reg['descricao']);
                $pasta->setTipoPasta($reg['tipo_pasta']);
                if($cont>1){
                    $arrayRetorno[] = $pasta;
                }else{
                    return $pasta;
                }
            }
            return $arrayRetorno;
            
        }
        
        return false;
    }
}