<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProjetosComunidades', 'doctrine');

/**
 * BaseProjetosComunidades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_conjunto_comunidade
 * @property integer $id_tipo_conjunto_comunidade
 * @property integer $id_comunidade
 * @property integer $id_conjunto_conteudo
 * @property integer $id_tipo_conjunto_conteudo
 * @property integer $id_conteudo
 * 
 * @method integer             getIdConjuntoComunidade()        Returns the current record's "id_conjunto_comunidade" value
 * @method integer             getIdTipoConjuntoComunidade()    Returns the current record's "id_tipo_conjunto_comunidade" value
 * @method integer             getIdComunidade()                Returns the current record's "id_comunidade" value
 * @method integer             getIdConjuntoConteudo()          Returns the current record's "id_conjunto_conteudo" value
 * @method integer             getIdTipoConjuntoConteudo()      Returns the current record's "id_tipo_conjunto_conteudo" value
 * @method integer             getIdConteudo()                  Returns the current record's "id_conteudo" value
 * @method ProjetosComunidades setIdConjuntoComunidade()        Sets the current record's "id_conjunto_comunidade" value
 * @method ProjetosComunidades setIdTipoConjuntoComunidade()    Sets the current record's "id_tipo_conjunto_comunidade" value
 * @method ProjetosComunidades setIdComunidade()                Sets the current record's "id_comunidade" value
 * @method ProjetosComunidades setIdConjuntoConteudo()          Sets the current record's "id_conjunto_conteudo" value
 * @method ProjetosComunidades setIdTipoConjuntoConteudo()      Sets the current record's "id_tipo_conjunto_conteudo" value
 * @method ProjetosComunidades setIdConteudo()                  Sets the current record's "id_conteudo" value
 * 
 * @package    robolivre
 * @subpackage model
 * @author     Max Guenes
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProjetosComunidades extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('projetos_comunidades');
        $this->hasColumn('id_conjunto_comunidade', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_tipo_conjunto_comunidade', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_comunidade', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_conjunto_conteudo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('id_tipo_conjunto_conteudo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_conteudo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}