Comunidades:
  connection: doctrine
  tableName: comunidades
  columns:
    id_comunidade:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_tipo_conjunto:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    id_conjunto:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nome:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descricao:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Conjuntos:
  connection: doctrine
  tableName: conjuntos
  columns:
    id_conjunto:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    id_tipo_conjunto:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    id_usuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    imagem_perfil:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    slug:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ultima_modificacao:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    data_criacao:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
DiariosBordo:
  connection: doctrine
  tableName: diarios_bordo
  columns:
    id_diario_bordo:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    id_conteudo:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_conjunto:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_tipo_conjunto:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    id_usuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nome:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descricao:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Documentos:
  connection: doctrine
  tableName: documentos
  columns:
    id_documento:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    id_usuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_pasta:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    nome_arquivo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    is_codigo_fonte:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    repositorio_github:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ordenacao:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    nome_documento:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    hits:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      default: '0'
      notnull: true
      autoincrement: false
Imagens:
  connection: doctrine
  tableName: imagens
  columns:
    id_imagem:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    id_usuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_pasta:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    nome_arquivo:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ordenacao:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
MensagensDestinatarios:
  connection: doctrine
  tableName: mensagens_destinatarios
  columns:
    id_mensagem:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    id_usuario_destinatario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_usuario_remetente:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
ParticipantesConjuntos:
  connection: doctrine
  tableName: participantes_conjuntos
  columns:
    id_usuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_conjunto:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_tipo_conjunto:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    id_tipo_permissao_conjunto:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    aceito:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      default: '1'
      notnull: true
      autoincrement: false
Pastas:
  connection: doctrine
  tableName: pastas
  columns:
    id_pasta:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    id_usuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_tipo_conjunto:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    id_conjunto:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nome:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descricao:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    tipo_pasta:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
ProjetosComunidades:
  connection: doctrine
  tableName: projetos_comunidades
  columns:
    id_conjunto_comunidade:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_tipo_conjunto_comunidade:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    id_comunidade:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_conjunto_conteudo:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_tipo_conjunto_conteudo:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    id_conteudo:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
SuperTipos:
  connection: doctrine
  tableName: super_tipos
  columns:
    id_super_tipo:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    nome:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descricao:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
TiposConjuntos:
  connection: doctrine
  tableName: tipos_conjuntos
  columns:
    id_tipo_conjunto:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    nome:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descricao:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
TiposPermissoesConjuntos:
  connection: doctrine
  tableName: tipos_permissoes_conjuntos
  columns:
    id_tipo_permissao_conjunto:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    id_tipo_conjunto:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: false
    nome:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    descricao:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
Usuarios:
  connection: doctrine
  tableName: usuarios
  columns:
    id_usuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nivel_escolaridade:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    nome:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    login:
      type: string(45)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    senha:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    endereco:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    habilidades:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    curso:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    site:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    site_empresa:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    data_nascimento:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    sexo:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      notnull: false
      autoincrement: false
    administrador:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    sobre_mim:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    ativo:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      default: '1'
      notnull: false
      autoincrement: false
    imagem_perfil:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    twitter:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    parametros_email:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    aula_robolivre:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: false
      default: '0'
      notnull: false
      autoincrement: false
    profissao:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    escola:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    empresa:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    data_criacao_perfil:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    token:
      type: string(20)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
